language: node_js
dist: jammy
node_js:
  - "16"

git:
  depth: false

install:
  - npm install
  - curl -sL https://sentry.io/get-cli/ | bash

script:
  - npm test

after_success:
  - node app.js &
  - sleep 5
  - curl http://localhost:3000/error || true
  - curl http://localhost:3000/async-error || true

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
