language: node_js
node_js:
  - "18"

install:
  - npm install
  - curl -sL https://sentry.io/get-cli/ | bash

script:
  - npm test

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
