language: node_js
dist: jammy
node_js:
  - "16"

git:
  depth: false

install:
  - npm install
  - npm install @sentry/tracing --save
  - curl -sL https://sentry.io/get-cli/ | bash

script:
  - npm test

after_success:
  - echo "Starting app in background..."
  - node app.js > app.log 2>&1 &
  - echo "Waiting for app to respond on /healthz..."
  - for i in {1..10}; do
      curl -s http://localhost:3000/healthz && break;
      echo "Retry $i: App not ready yet...";
      sleep 1;
    done
  - echo "Hitting test error routes..."
  - curl -s http://localhost:3000/error || true
  - curl -s http://localhost:3000/async-error || true
  - echo "Error routes triggered. Check Sentry dashboard."

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
