language: node_js
dist: jammy
node_js:
  - "16"

git:
  depth: false

install:
  - npm install
  - curl -sL https://sentry.io/get-cli/ | bash
  - npm install @sentry/tracing --save

script:
  - echo "Running tests..."
  - npm test

after_success:
  - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
  - curl -Os https://cli.codecov.io/latest/linux/codecov
  - curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM
  - curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM.sig
  - gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
  - shasum -a 256 -c codecov.SHA256SUM
  - chmod +x codecov
  - ./codecov --token=${CODECOV_TOKEN}
  - ./codecov upload-process -r Montana/travis-sentry

  - node app.js > app.log 2>&1 &
  - >
    for i in {1..10}; do
      if curl -s http://localhost:3000/healthz; then
        echo "App is healthy.";
        break;
      fi;
      echo "Attempt $i: App not ready, retrying in 1s...";
      sleep 1;
    done
  - if ! curl -s http://localhost:3000/healthz; then
      echo "App failed to start or respond to healthz.";
      echo "--- APP LOG ---";
      cat app.log;
      exit 1;
    fi
  - curl -s http://localhost:3000/error || true
  - curl -s http://localhost:3000/async-error || true

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
