codecov:
  require_ci_to_pass: true
  token: ${CODECOV_TOKEN}
comment:
  behavior: default
  layout: reach, diff, flags, files
  require_changes:
  - 1
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes:
      default:
        enabled: true
    patch:
      default:
        target: 75.0
        threshold: 1.0
    project:
      default:
        base: auto
        target: 85.0
        threshold: 2.0
flags:
  package-a:
    carryforward: true
    paths:
    - ^packages/package-a/.*
  package-b:
    carryforward: true
    paths:
    - ^packages/package-b/.*
  shared:
    carryforward: true
    paths:
    - ^packages/shared/.*
ignore:
- ^test/.*
- (?s:.*/[^\/]*\.test\.js)\Z
- (?s:.*/__mocks__/.*)\Z
- ^node_modules/.*
- ^coverage/.*
parsers:
  javascript:
    enable_partials: true
